version: '3'
services:
  web:
    build: .
    command: bundle exec rackup --host 0.0.0.0 --port 3000
    volumes:
      - .:/app
      - bundle-data:/usr/local/bundle
    working_dir: /app
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=hogehoge
      - MYSQL_DATABASE=myserver
    tty: true
    stdin_open: true
    ports:
      - 3000:3000

  mysql:
    image: mysql:8
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: hogehoge
      MYSQL_DATABASE: myserver

volumes:
  bundle-data:
    driver: local
  mysql-data:
    driver: local
